// src/config.ts
export const CONFIG = {
  MAX_PARTICIPANTS_PER_EVENT: 50,
  MAX_EVENT_TITLE_LENGTH: 100,
  MAX_COMMENT_LENGTH: 500,
  MAX_TIMESTAMP_YEAR: 2035,
  DM_RATE_LIMIT_MS: 200,
  USER_FETCH_TIMEOUT_MS: 5000,
  BUTTON_COOLDOWN_MS: 2000,
  EMBED_PARTICIPANTS_FIELD_LIMIT: 900,
} as const;
